# <center>Démarrage rapide de TensorFlow 2 pour les débutants </center>

**Source :** https://www.tensorflow.org/tutorials/quickstart/beginner?hl=fr

Contenu :

- Charger un jeu de données prédéfini.
- Créer un modèle d'apprentissage automatique de réseau neuronal qui classe les images.
- Entraîner ce réseau de neurones.
- Évaluer la précision du modèle.

## Configuration de TensorFlow

In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.11.0


## Chargement du jeu de données

In [9]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
# conversion en float
x_train, x_test = x_train / 255.0, x_test / 255.0

## Créer un modèle d'apprentissage automatique

In [10]:
model = tf.keras.models.Sequential([
    # empilement des couches
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

## Faire des prédictions

In [11]:
# Pour chaque exemple, le modèle renvoie un vecteur de scores logits ou log-odds , un pour chaque classe.
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.3776231 , -0.7269157 ,  0.25920781,  0.1783102 ,  0.00217468,
        -0.31357008,  0.05425137, -0.01190896, -0.0044143 , -0.7873131 ]],
      dtype=float32)

In [12]:
# La fonction tf.nn.softmax convertit ces logits en probabilités pour chaque classe :
tf.nn.softmax(predictions).numpy()

array([[0.07712895, 0.05439031, 0.14581075, 0.13447952, 0.11276167,
        0.08223095, 0.11878952, 0.1111847 , 0.11202113, 0.05120251]],
      dtype=float32)

## Fonction de perte

Définissez une fonction de perte pour l'entraînement à l'aide `losses.SparseCategoricalCrossentropy` , qui prend un vecteur de logits et un indice True et renvoie une perte scalaire pour chaque exemple.

In [13]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

Cette perte est égale à la probabilité logarithmique négative de la vraie classe : la perte est nulle si le modèle est sûr de la bonne classe.

Ce modèle non formé donne des probabilités proches du hasard (1/10 pour chaque classe), donc la perte initiale devrait être proche de `-tf.math.log(1/10) ~= 2.3` .

In [14]:
loss_fn(y_train[:1], predictions).numpy()

2.4982235

## Compilation du modèle

Avant de commencer l'entraînement, configurez et compilez le modèle à l'aide de Keras `Model.compile`. Définissez la classe d' optimizer sur `adam` , définissez la `loss` sur la fonction `loss_fn` que vous avez définie précédemment et spécifiez une métrique à évaluer pour le modèle en définissant le `metrics` sur `accuracy` .

In [15]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

## Entraînement du modèle

In [16]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 13s 6ms/step - loss: 0.2982 - accuracy: 0.9136
Epoch 2/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1459 - accuracy: 0.9565
Epoch 3/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1084 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0869 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0746 - accuracy: 0.9765


## Evaluation du modèle (sur le jeu de test)

In [17]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0768 - accuracy: 0.9751 - 1s/epoch - 5ms/step


[0.07680600136518478, 0.9750999808311462]

### Renvoyer une probabilité avec *softmax*

In [19]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [20]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.7866327e-09, 5.7784561e-08, 7.2966776e-07, 6.0225826e-05,
        5.4439120e-11, 3.2478272e-07, 3.1732366e-12, 9.9993873e-01,
        7.7195894e-09, 1.0943701e-08],
       [1.1618745e-08, 2.0467989e-04, 9.9979502e-01, 1.6546451e-08,
        6.2384146e-18, 1.3397424e-08, 1.7880294e-07, 1.6897603e-15,
        2.4508504e-09, 2.2900107e-16],
       [1.7433520e-06, 9.9840087e-01, 3.3884964e-04, 1.5053068e-05,
        2.3023806e-05, 7.5220382e-06, 2.2722325e-05, 9.1033004e-04,
        2.7417834e-04, 5.7489347e-06],
       [9.9971884e-01, 4.3797620e-08, 6.3468222e-05, 1.5121509e-08,
        7.2885018e-07, 6.7891328e-06, 1.8851610e-04, 3.1102545e-06,
        1.1379843e-07, 1.8335082e-05],
       [1.2082776e-06, 1.6642185e-08, 1.7685231e-06, 1.3185909e-08,
        9.9988210e-01, 1.1162044e-06, 1.0253473e-06, 1.6977603e-05,
        3.0288427e-07, 9.5497613e-05]], dtype=float32)>