# <center> Un exemple de One-hot encondig avec Sklearn </center>

## Importations :

In [9]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

## Exemple :

In [11]:
# appel des modules
label_encoder = LabelEncoder()
encoder = OneHotEncoder()

# variables qualitatives
qualitative = ['vert', 'bleu', 'rouge', 'vert', 'rouge', 'orange', 'jaune']

# application 
labels = label_encoder.fit_transform(qualitative).reshape(len(qualitative), 1)

# variables quantitatives
quantitative = encoder.fit_transform(labels).toarray()
print(quantitative)

[[0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]]
