# <center> Bibliothèques externes sous Python </center>

**Source :**
- Revue Coding, "Apprenez à travailler avec des bibliothèques externes sous Python", Hors série n°16, p.50-53.

## Exemple : le module math (bibliothèque standard)

In [1]:
import math
print("Le module math a un type {}".format(type(math)))

Le module math a un type <class 'module'>


**Math** est un module. Un module est juste une collection de variables définies par une personne qui l'a développé. 

## Fonction **`dir()`**

In [3]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


### Exemple : 

In [4]:
# valeur simple
math.pi

3.141592653589793

In [5]:
# fonction
math.log(32, 2)

5.0

## Fonction **`help()`**

In [6]:
# détaille la fonction indiquée
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [8]:
# détaille le module lui-même
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
        
        This is the smallest integer >= x.
    
    comb(n, k, /)
        Number of ways to choose k items from n items without repetition and without order

## Abréviations lors d'importation

In [9]:
import math as mt
import pandas as pd
import numpy as np

In [10]:
mt.pi

3.141592653589793

## Tout importer 

In [12]:
from math import *

print(pi, log(32, 2))

3.141592653589793 5.0


**A éviter** : risque d'erreur si deux modules ont le même nom de fonction. Exemple numpy et math avec la fonction **log**.

## Importer uniquement ce qui est nécessaire

In [13]:
from math import log, pi
from numpy import asarray

---

# Sous-modules

In [24]:
import numpy

print(numpy.random.randint)
print(type(numpy.random))
print(type(numpy.random.randint))

<built-in method randint of numpy.random.mtrand.RandomState object at 0x000002253729A540>
<class 'module'>
<class 'builtin_function_or_method'>


In [22]:
a = numpy.random.randint(low=1, high=6, size=10)
a

array([4, 4, 1, 3, 5, 4, 2, 5, 3, 5])

In [25]:
# savoir ce dont il s'agit
type(a)

numpy.ndarray

In [27]:
# savoir ce qu'on peut faire avec
print(dir(a))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [31]:
# afficher l'aide en ligne
help(a.ravel)

# help(a) = aide très longue
# ... mieux vaut la consulter en ligne.

Help on built-in function ravel:

ravel(...) method of numpy.ndarray instance
    a.ravel([order])
    
    Return a flattened array.
    
    Refer to `numpy.ravel` for full documentation.
    
    See Also
    --------
    numpy.ravel : equivalent function
    
    ndarray.flat : a flat iterator on the array.



## Surcharge de l'opérateur 

In [32]:
a

array([4, 4, 1, 3, 5, 4, 2, 5, 3, 5])

In [33]:
a + 10

array([14, 14, 11, 13, 15, 14, 12, 15, 13, 15])

On ne peux pas faire `liste + 10` (erreur) mais on peut faire `tableau numpy + 10` (ajoute le nombre à chaque élément du tableau). 

In [34]:
liste = [x for x in range(10)]
liste

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
# idems avec d'autres opérateurs
a <= 3

array([False, False,  True,  True, False, False,  True, False,  True,
       False])

### Créer un tableau à deux dimensions

In [42]:
# type : list
xlist = [[1, 2, 3],[2, 4, 6]]

# transforme en array :
x = numpy.asarray(xlist)

In [43]:
type(x)

numpy.ndarray

In [48]:
# liste
print(xlist)

[[1, 2, 3], [2, 4, 6]]


In [49]:
# tableau numpy
print(x)

[[1 2 3]
 [2 4 6]]


### Afficher le dernier élément de la deuxième ligne du tableau

In [50]:
x[1, -1]

6

## Afficher la dernière ligne

In [51]:
x[-1]

array([2, 4, 6])