# <center> Manipulation avec Numpy </center>

## Utilisation de `reshape()`

In [3]:
# création d'une liste
mylist = [x for x in range(1, 9)]

print(mylist)

[1, 2, 3, 4, 5, 6, 7, 8]


### Transformation en *array* (vecteur)

In [4]:
import numpy as np

myList = np.array(mylist)

print(mylist)

[1, 2, 3, 4, 5, 6, 7, 8]


### Transformation en matrices de 2 dimensions

In [11]:
print(myList.reshape(2,4))

[[1 2 3 4]
 [5 6 7 8]]


### Transformation en matrices de 3 dimensions

In [13]:
print(myList.reshape(2,2,2))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


--- 

## Opérations sur des matrices

### Transposition

La transposition se produit lorsqu'une matrice de forme `n x m` est transformée en une matrice `m x n` en échangeant les lignes avec les colonnes.

In [9]:
matrice = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(matrice, end="\n\n")
print("Transposition : \n")
print(np.transpose(matrice))

[[1 2 3 4]
 [5 6 7 8]]

Transposition : 

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


### Matrice identité

In [10]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Inversion de matrice (avec `linalg.inv`)

In [15]:
a = np.array([[1,2], [3,4]])
b = np.linalg.inv(a)

print("Matrice :\n", a, end="\n\n")
print("Matrice inversée :\n", b)

Matrice :
 [[1 2]
 [3 4]]

Matrice inversée :
 [[-2.   1. ]
 [ 1.5 -0.5]]


### Comparer les deux matrices (avec `allclose`)

In [16]:
print(np.allclose(np.dot(a,b), np.identity(2)))

True


---

## Multiplier des *inputs* par des poids (*weights*)

In [20]:
inputs = np.array([5, 10, 15])
print(inputs)

[ 5 10 15]


In [21]:
weights = np.array([[.5,.2,-1], [.3,.4,.1], [-.2,.1,.3]])
print(weights)

[[ 0.5  0.2 -1. ]
 [ 0.3  0.4  0.1]
 [-0.2  0.1  0.3]]


In [22]:
# multiplication
result = np.dot(inputs, weights)
print(result)

[2.5 6.5 0.5]


--- 

## Manipuler des vecteurs

### Additionner des vecteurs

In [23]:
def Add(a, b):
    return a + b

resultat = np.vectorize(Add)

print(resultat([1, 2, 3, 4], [1, 2, 3, 4]))

[2 4 6 8]
